### ISSUE TITLE
Attempting to attack a tamed fox caused a crash (1.12.2)

### ISSUE THREAD

**Issue by Vulpixy** [ItsTheKais/Outfox#5]
While attempting to replicate a bug where dogs from Doggy Talents attacked a tamed fox, I crashed as I tried to hit the fox. I was able to attack them before setting up the test so I'm not sure what caused the crash.

* Minecraft version: 1.12.2
* Forge version: 14.23.4.2758
* Outfox Version: 0.1.2
* Doggy Talents Version: 1.14.2.321

<details><summary>Crash Log</summary>
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 9/3/18 3:39 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Invalid hand null
	at net.minecraft.entity.EntityLivingBase.func_184586_b(EntityLivingBase.java:1633)
	at kais.outfox.fox.EntityFox.func_85031_j(EntityFox.java:347)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1253)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78764_a(PlayerControllerMP.java:540)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1510)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2248)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2019)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1807)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.entity.EntityLivingBase.func_184586_b(EntityLivingBase.java:1633)
	at kais.outfox.fox.EntityFox.func_85031_j(EntityFox.java:347)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1253)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78764_a(PlayerControllerMP.java:540)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1510)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2248)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2019)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Vulpixy'/54, l='MpServer', x=-805.05, y=4.00, z=-418.71]]
	Chunk stats: MultiplayerChunkCache: 784, 784
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-814,4,-415), Chunk: (at 2,0,1 in -51,-26; contains blocks -816,0,-416 to -801,255,-401), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 8062 game time, 8062 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 23 total; [EntityChicken['Chicken'/32, l='MpServer', x=-804.20, y=4.00, z=-399.47], EntityItem['item.item.egg'/33, l='MpServer', x=-807.14, y=4.00, z=-369.14], EntityCow['Cow'/34, l='MpServer', x=-801.50, y=4.00, z=-356.50], EntityCow['Cow'/35, l='MpServer', x=-800.50, y=4.00, z=-358.50], EntityChicken['Chicken'/36, l='MpServer', x=-801.50, y=4.00, z=-357.50], EntityItem['item.item.egg'/37, l='MpServer', x=-801.69, y=4.00, z=-357.74], EntityItem['item.item.egg'/38, l='MpServer', x=-797.93, y=4.00, z=-404.01], EntityPig['Pig'/39, l='MpServer', x=-796.26, y=4.00, z=-382.45], EntityChicken['Chicken'/40, l='MpServer', x=-799.86, y=4.00, z=-375.21], EntityChicken['Chicken'/41, l='MpServer', x=-789.27, y=4.00, z=-443.11], EntitySheep['Sheep'/42, l='MpServer', x=-738.68, y=4.00, z=-433.69], EntitySheep['Sheep'/43, l='MpServer', x=-749.55, y=4.00, z=-444.20], EntitySheep['Sheep'/44, l='MpServer', x=-741.80, y=4.00, z=-434.65], EntitySheep['Sheep'/45, l='MpServer', x=-744.66, y=4.00, z=-423.76], EntityPlayerSP['Vulpixy'/54, l='MpServer', x=-805.05, y=4.00, z=-418.71], EntityChicken['Chicken'/24, l='MpServer', x=-802.83, y=4.00, z=-458.28], EntityPig['Pig'/25, l='MpServer', x=-807.22, y=4.00, z=-462.34], EntityItem['item.item.egg'/26, l='MpServer', x=-801.98, y=4.00, z=-458.77], EntitySheep['Sheep'/27, l='MpServer', x=-812.75, y=4.00, z=-430.55], EntityFox['Fox'/28, l='MpServer', x=-802.95, y=4.00, z=-418.20], EntityFox['Peach'/29, l='MpServer', x=-811.48, y=4.00, z=-417.48], EntityWolf['Mario'/30, l='MpServer', x=-805.70, y=4.00, z=-415.24], EntityDog['Bowser'/31, l='MpServer', x=-803.53, y=4.00, z=-411.58]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1077688504 bytes (1027 MB) / 2234515456 bytes (2131 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1G -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=40
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2758 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID           | Version      | Source                                        | Signature |
	|:--------- |:------------ |:------------ |:--------------------------------------------- |:--------- |
	| UCHIJAAAA | minecraft    | 1.12.2       | minecraft.jar                                 | None      |
	| UCHIJAAAA | mcp          | 9.42         | minecraft.jar                                 | None      |
	| UCHIJAAAA | FML          | 8.0.99.99    | forge-1.12.2-14.23.4.2758.jar                 | None      |
	| UCHIJAAAA | forge        | 14.23.4.2758 | forge-1.12.2-14.23.4.2758.jar                 | None      |
	| UCHIJAAAA | doggytalents | 1.14.2.321   | Doggy+Talents-1.12.2-1.14.2.321-universal.jar | None      |
	| UCHIJAAAA | outfox       | 0.1.2        | outfox-0.1.2-mc1.12.2.jar                     | None      |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.82' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2758
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.82, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3 CPU 540 @ 3.07GHz
</details>

**Comment by ItsTheKais** [comment]
Looks like I missed a null check somewhere, should be a straightforward fix.

**Comment by Vulpixy** [comment]
Sweet, I'm glad it will be a (hopefully) easy fix. Do you have an ETA on when the next update can be expected?
